# Generated by Django 5.1.4 on 2025-01-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='code',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(help_text='Category of the product', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_net_weight',
            field=models.FloatField(default=0, help_text='Net weight of the product in grams or kg'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.FloatField(default=0, help_text='Price of the product'),
        ),
    ]
