# Generated by Django 5.1.4 on 2025-01-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_products_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField(help_text='ID of the buyer')),
                ('product_id', models.IntegerField(help_text='ID of the product being ordered')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of the product being ordered')),
                ('price', models.FloatField(default=0, help_text='Price of the product at the time of purchase')),
                ('address', models.TextField(help_text='Delivery address for the order')),
                ('mobile_number', models.CharField(help_text='Mobile number of the buyer', max_length=15)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('cash_on_delivery', 'Cash on Delivery')], default='credit_card', help_text='Method of payment', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the order was placed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', help_text='Order status', max_length=20)),
            ],
        ),
    ]
